<h1>Novo Usuario</h1>

<form method="post" action="">
    <label for="nome">Nome</label>
    <input id="nome" class="form-control mb-3" name="nome">

    <label for="email">Email</label>
    <input id="email" class="form-control mb-3" name="email">

    <label for="senha">Senha</label>
    <input id="senha" type="password" class="form-control mb-3" name="senha">

    <button class="btn btn-primary">PRONTO</button>
</form>