<h1>Lista de Produtos</h1>

<table class="table table-striped table-hover mt-3">
    <thead class="table-dark">
        <tr>
            <th>Nome</th>
            <th>Valor</th>
            <th>Quantidade</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($dados as $cada) {
                echo "<tr>
                    <td>{$cada['nome']}</td>
                    <td>{$cada['valor']}</td>
                    <td>{$cada['quantidade']}</td>
                    <td> 
                        <a class='btn btn-outline-danger' href='/produtos/excluir?id={$cada['id']}'>Excluir</a>
                    </td>
                </tr>";
            }
        ?>
    </tbody>
</table>