<nav class="mb-3">
    <a class="btn btn-outline-dark" href="/">Inicio</a>
    <a class="btn btn-outline-dark" href="/restaurantes">Restaurantes</a>
    <a class="btn btn-outline-dark" href="/produtos">Produtos</a>
    <a class="btn btn-outline-dark" href="/contato">Contato</a>
    <a class="btn btn-outline-dark" href="/admin">Admin</a>

    <a class="btn btn-outline-danger" href="/logout">Sair</a>
</nav>

