<h1>Lista de Restaurantes (<?php echo App\Model\Restaurante::count() ?>)</h1>

<a href="/restaurantes/cadastro">Add Restaurante</a>

<a target="_blank" href="/restaurantes/pdf">Gerar PDF</a>

<table class="table table-striped table-hover mt-3">
    <thead class="table-dark">
        <tr>
            <th>Nome</th>
            <th>Endereço</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($dados as $cada) {
                echo "<tr>
                    <td>{$cada['nome']}</td>
                    <td>{$cada['endereco']}</td>
                    <td>
                        <a href='/restaurantes/excluir?id={$cada['id']}' class='btn btn-outline-danger'>Excluir</a>
                        <a href='/restaurantes/editar?id={$cada['id']}' class='btn btn-outline-warning'>Editar</a>
                    </td>
                </tr>";
            }
        ?>
    </tbody>
</table>