<section class="row">
    <div class="col-4 offset-4">
        <div class="card card-body">
            <form method="post" action="">
                <input name="email" placeholder="Email" class="form-control form-control-lg mb-3">
                <input name="senha" type="password" placeholder="Senha" class="form-control form-control-lg mb-3">

                <button class="btn btn-dark w-100">ENTRAR</button>
            </form>
        </div>
    </div>
</section>

